# Site settings
title: Welcome to GiPHouse!
email: 
description: > # this means to ignore newlines until "baseurl:"
       GiPHouse is a unique student-run company that develops
       software and practices entrepreneurship at the Radboud
       University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: giphouse
github_username:  giphouse

# Build settings
markdown: kramdown
